# Generated by Django 3.1.2 on 2020-12-29 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving', models.IntegerField()),
                ('other', models.IntegerField()),
                ('emergency', models.IntegerField()),
                ('months', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_income', models.IntegerField()),
                ('fixed_income2', models.IntegerField()),
                ('fixed_income3', models.IntegerField()),
                ('extra_income', models.IntegerField()),
                ('food_expenses', models.IntegerField()),
                ('transport_expenses', models.IntegerField()),
                ('health_expenses', models.IntegerField()),
                ('education_expenses', models.IntegerField()),
                ('clothing_expenses', models.IntegerField()),
                ('subscription_expenses', models.IntegerField()),
                ('rent_expenses', models.IntegerField()),
                ('common_expenses', models.IntegerField()),
                ('billing_expenses', models.IntegerField()),
                ('phone_cable_internet_expenses', models.IntegerField()),
                ('insurance_expenses', models.IntegerField()),
                ('entertainment_expenses', models.IntegerField()),
                ('objective', models.CharField(choices=[(0, 'Comprar un departamento o casa'), (1, 'Pagar mi educación'), (2, 'Viajar'), (3, 'Emprender un negocio o nuevo proyecto'), (4, 'Para mi jubilación'), (5, 'Invertir mi dinero'), (6, 'Pagar algún tipo de seguro o deuda'), (7, 'Otro objetivo de ahorro'), (8, 'No tengo ningún objetivo de ahorro en mente')], max_length=100)),
                ('obj_savings', models.IntegerField()),
                ('obj_months', models.IntegerField()),
                ('extra_expenses', models.IntegerField()),
                ('emergency_fund', models.IntegerField()),
                ('alert_freq', models.IntegerField()),
                ('alert_type', models.CharField(choices=[(0, 'Saldo bajo en cuenta'), (1, 'Movimientos duplicados'), (2, 'Resumen semanal de tu control financiero'), (3, 'Resumen mensual de tu control financiero'), (4, 'Proyección del ahorro'), (5, 'Dinero restante por cumplir la cuota mensual de ahorro')], max_length=100)),
                ('media', models.CharField(choices=[(0, 'Whatsapp'), (1, 'Email')], max_length=20)),
                ('phone_number', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
