# Generated by Django 3.1.2 on 2020-12-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201231_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='alert_freq',
            field=models.CharField(choices=[('1 vez por semana', '1 vez por semana'), ('2 veces por semana', '2 veces por semana'), ('3 veces por semana', '3 veces por semana')], max_length=20),
        ),
    ]
