# Generated by Django 3.1.2 on 2020-12-31 15:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201231_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='alert_freq',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1 vez por semana', '1 vez por semana'), ('2 veces por semana', '2 veces por semana'), ('3 veces por semana', '3 veces por semana')], max_length=255),
        ),
        migrations.AlterField(
            model_name='financial',
            name='media',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email')], max_length=255),
        ),
    ]
