# Generated by Django 3.1.2 on 2020-12-31 16:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201231_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='alert_freq',
            field=models.CharField(choices=[('1 vez por semana', '1 vez por semana'), ('2 veces por semana', '2 veces por semana'), ('3 veces por semana', '3 veces por semana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financial',
            name='alert_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Saldo bajo en cuenta', 'Saldo bajo en cuenta'), ('Movimientos duplicados', 'Movimientos duplicados'), ('Resumen semanal de tu control financiero', 'Resumen semanal de tu control financiero'), ('Resumen mensual de tu control financiero', 'Resumen mensual de tu control financiero'), ('Proyección del ahorro', 'Proyección del ahorro'), ('Dinero restante por cumplir la cuota mensual de ahorro', 'Dinero restante por cumplir la cuota mensual de ahorro')], max_length=255),
        ),
    ]
